// Runs every scenario twice, with the two people's Yjs client IDs swapped,
// plus the random-edit run, and writes the results table into the research
// docs. Deterministic: the same code gives the same file.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { expect, test } from 'vitest';
import { basePlan, canonical, pair, plan } from './harness.ts';
import { fuzz } from './fuzz.ts';
import { scenarios, type Verdict } from './scenarios.ts';

const OUT = fileURLToPath(new URL('../../docs/research/collaboration/merge-results.md', import.meta.url));

interface Row {
  id: string;
  title: string;
  setting: string;
  alice: string;
  bob: string;
  expected: string;
  result: string;
  verdict: Verdict;
  converged: boolean;
  /** The other run, with client IDs swapped, if it came out differently. */
  swapped: string | null;
}

test('merge scenarios', () => {
  const rows: Row[] = scenarios.map((s) => {
    const one = pair(basePlan(), true);
    const first = s.run(one);
    const two = pair(basePlan(), false);
    const second = s.run(two);
    return {
      id: s.id,
      title: s.title,
      setting: s.setting,
      alice: s.alice,
      bob: s.bob,
      expected: s.expected,
      result: first.result,
      verdict: first.verdict,
      converged: canonical(plan(one.alice)) === canonical(plan(one.bob)) && canonical(plan(two.alice)) === canonical(plan(two.bob)),
      swapped: second.result === first.result ? null : second.result,
    };
  });
  const f = fuzz(20, 150);

  const counts = new Map<Verdict, number>();
  for (const r of rows) counts.set(r.verdict, (counts.get(r.verdict) ?? 0) + 1);
  const order: Verdict[] = ['as expected', 'coin toss', 'surprising', 'work lost', 'bad state'];

  const lines: string[] = [
    '# Merge scenarios: results',
    '',
    '_Generated by `spikes/merge-scenarios/` (`npx vitest run --config spikes/merge-scenarios/vitest.config.ts`). Don\'t edit by hand. The reading of these results is in [`merge-scenarios.md`](merge-scenarios.md)._',
    '',
    'Two people, Alice and Bob, start on the same ten-card board and edit it through the app\'s real commands. "Live" means both edit within the same second or so, before either sees the other\'s change. "Offline" means one of them works disconnected for a while. Then their documents sync.',
    '',
    'Every scenario runs twice, with the two people\'s Yjs client IDs swapped. Client IDs are random per session, so a result that changes when they\'re swapped is a coin toss that nobody chose.',
    '',
    `**Verdicts:** ${order.map((v) => `${counts.get(v) ?? 0} ${v}`).join(', ')}. Every scenario converged: both people see the same board afterwards (${rows.every((r) => r.converged) ? 'yes' : 'NO'}).`,
    '',
    '| # | Scenario | Setting | Verdict | Swapping client IDs |',
    '|---|---|---|---|---|',
    ...rows.map((r) => `| ${r.id} | ${r.title} | ${r.setting} | ${r.verdict} | ${r.swapped === null ? 'same result' : 'different result'} |`),
    '',
    '## Each scenario',
    '',
  ];
  for (const r of rows) {
    lines.push(`### ${r.id}: ${r.title}`, '');
    lines.push(`- **Alice:** ${r.alice}`, `- **Bob:** ${r.bob}`, `- **Expected:** ${r.expected}`, `- **Result:** ${r.result}`);
    if (r.swapped !== null) lines.push(`- **With client IDs swapped:** ${r.swapped}`);
    lines.push(`- **Verdict:** ${r.verdict}`, '');
  }
  lines.push(
    '## Random edits',
    '',
    `${f.seeds} runs. In each, Alice and Bob make ${f.editsEach} random edits apiece while apart (drags, Alt-drops, renames, nesting, new cards, links, sizes and the odd delete), then sync once.`,
    '',
    '| Measure | Total over all runs |',
    '|---|---|',
    `| Runs where both boards converged | ${f.converged} of ${f.seeds} |`,
    `| Cards afterwards | ${f.cards} |`,
    `| Cards holding two quarters | ${f.twoQuarters} |`,
    `| Cards holding two sizes | ${f.twoSizes} |`,
    `| Cards whose group was deleted (shown at the top level) | ${f.orphans} |`,
    `| Cards on a loop of parents (shown at the top level) | ${f.cycles} |`,
    `| Links stored to a deleted card (hidden) | ${f.danglingLinks} |`,
    '',
  );
  writeFileSync(OUT, lines.join('\n'));
  expect(rows.filter((r) => !r.converged).map((r) => r.id)).toEqual([]);
  expect(f.converged).toBe(f.seeds);
});
